package core

const (
	stageTargetReceived         = "target.received"
	stageTargetClassify         = "target.classify"
	stageAPITestingRecon        = "api-testing.recon"
	stageAPITestingAccess       = "api-testing.access-control"
	stageAPITestingRateLimit    = "api-testing.rate-limit"
	stageAPITestingInjection    = "api-testing.injection"
	stageAPITestingGraphQL      = "api-testing.graphql"
	stageAPITestingFuzzing      = "api-testing.fuzzing"
	stageAPITestingComplete     = "api-testing.complete"
	stageApplicationMappingExplore       = "application-mapping.explore"
	stageApplicationMappingEntryPoints   = "application-mapping.entry-points"
	stageApplicationMappingMetadata      = "application-mapping.metadata-review"
	stageApplicationMappingAttackSurface = "application-mapping.attack-surface"
	stageApplicationMappingComplete      = "application-mapping.complete"
	stageActiveTestingAccessControl = "active-testing.access-control"
	stageActiveTestingBusinessLogic = "active-testing.business-logic"
	stageActiveTestingInputProbing  = "active-testing.input-probing"
	stageActiveTestingXSS           = "active-testing.xss"
	stageActiveTestingInjection     = "active-testing.injection"
	stageActiveTestingErrorHandling = "active-testing.error-handling"
	stageActiveTestingConfigChecks  = "active-testing.configuration-checks"
	stageActiveTestingComplete      = "active-testing.complete"
)
